server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/clear_page
spring.datasource.username=root
spring.datasource.password=#JAYA1708!!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Replace with actual API key at runtime if needed, can also use env variable
openai.api.key=${OPENAI_API_KEY:default_key}
